### ISSUE TITLE
Most ENV variables are not used causing errors

### ISSUE THREAD

**Issue by jmoflhrc** [lux4rd0/weatherflow-collector#1]
Thanks for all the work here, this is very cool.  I just updates to the latest release and now it seems the env variables are not passed.

Example of what I am currently seeing below clearing sensitive data.  This was working with the "latest" build I pulled on 4/8/2021

Starting WeatherFlow Collector (startup.sh) - https://github.com/lux4rd0/weatherflow-collector
Debug Environmental Variables
backend_type=influxdb
collector_type=remote-forecast
debug=true
device_id=
elevation=
forecast_interval=60
host_hostname=
hub_sn=
influxdb_password="DELETED BUT PRESENT"
influxdb_url="DELETED BUT PRESENT"
influxdb_username="DELETED BUT PRESENT"
latitude=
loki_client_url=
longitude=
public_name=
rest_interval=
station_id=
station_name=
timezone=
token=

**Comment by jmoflhrc** [comment]
Looking through the latest code change I see the variables changed going to edit my deployment now and see if that fixes things.

**Comment by jmoflhrc** [comment]
did the following and I'm working now:

removed:
 "_REMOTE" from a few variables

Added:
WEATHERFLOW_COLLECTOR_ELEVATION
WEATHERFLOW_COLLECTOR_HUB_SN
WEATHERFLOW_COLLECTOR_LATITUDE
WEATHERFLOW_COLLECTOR_LONGITUDE
WEATHERFLOW_COLLECTOR_PUBLIC_NAME
WEATHERFLOW_COLLECTOR_STATION_NAME
WEATHERFLOW_COLLECTOR_TIMEZONE

**Comment by lux4rd0** [comment]
Hey @jmoflhrc . Thanks for trying things out here. I've been messing with many of the scripts, and I'm afraid that it's been in a pretty good flux. I've been trying to get everything put back together but what I've found is that my tinkering is breaking stuff all over the place.

Can you try out the latest script that I just updated? I think it's pretty close. More details on how to use it is in the README file. I've only had my Tempest to try it out with, so I'd love any feedback you can provide. Thanks!

Once this docker container is buttoned up, I'll update the dashboards as well.

**Comment by jmoflhrc** [comment]
Thanks, going to read it over.  I'm using this a bit different since I'm running on Synology.  Using the GUI I've added the needed bits to each created container and it seems to be working fine.

I should have time this evening to update the latest image and re-deploy, also will be adding a 4th container for the remote import and trying that out!!

**Comment by lux4rd0** [comment]
Nice! I have a Synology as well and know that the Docker UI can be pretty helpful. But it's not docker-compose friendly :) Please share your outcomes as I'm interested in how you get along. I'll try it out myself, and if there's a way to update a script or make it easier to deploy that way - I'm certainly game for making updates.

**Comment by jmoflhrc** [comment]
Pulled 2.4.0 docker image and my "remote-socket", "local-udp", "remote-forecast" are working great with the same variables as yesterday.  I don't have the "remote-rest" setup yet but may...

Having issues with "remote-import" though, I've sanitized the output here, looks like the variable is seen but the container stops immediately. 

Starting WeatherFlow Collector (startup.sh) - https://github.com/lux4rd0/weatherflow-collector
Debug Environmental Variables
backend_type=influxdb
collector_type=remote-import
debug=true
device_id=*****
elevation=**
forecast_interval=60
host_hostname=
hub_sn=*******************
influxdb_password=*******************
influxdb_url=**************************
influxdb_username=*************
latitude=*******************
loki_client_url=
longitude=-*************
public_name=*************
rest_interval=60
station_id=**********
station_name=*****************
timezone=*****************************
token=**************************************
No Remote Collector Configured

**Comment by lux4rd0** [comment]
Depending on when you pulled that 2.4.0 image - it's possible that it's not really the latest version. I saw that happen in my testing against the latest flag in which I didn't do a new pull. 

Can you trying the :latest flag and see if it works?

**Comment by jmoflhrc** [comment]
I think the issue was between the chair and the keyboard here.  I pulled the 2.4.0 direct instead of latest.  Clearing and re-deploying now.

**Comment by jmoflhrc** [comment]
Looks like the import is flowing now, data is starting to populate in Grafana from June when I installed the weather station.  Looks like it's visible in the local-udp charts, nothing in remote yet.

Also the other 3 containers are still working on the 2.4.0 build.

**Comment by lux4rd0** [comment]
I have updated dashboards coming later tonight that you'll probably need to update as well. :) I pushed them to my AIO project but haven't rolled them back into these stand alone versions.

**Comment by lux4rd0** [comment]
Cool. Glad it's working. It will only import into the local-udp bucket since that's all that's available. There's no matching derived metrics / rest data available.
