### ISSUE TITLE
Large number of dns calls to swd.weatherflow.com

### ISSUE THREAD

**Issue by PianSom** [lux4rd0/weatherflow-collector#10]
Hello

I recently put a pihole container on my docker instance, and have found that the weather flow-collector container is making ~8.5k dns calls to swd.weatherflow.com each 24 hours (including both IPv4 and IPv6 calls), making it by far the largest client.

This isn't a huge issue, but it does suggest that maybe there is something inefficient in the code.

**Comment by lux4rd0** [comment]
@PianSom Appreciate the insights. I use Pihole as well and have similar visibility. I'm currently seeing:

136440 a day to swd.weatherflow.com and 122112 to ws.weatherflow.com. But I'm also polling a lot of different API keys.

By default, it's polling the Rest API every minute and the Forecast API every 15 minutes, and it's only one query. So the math doesn't add up.

Let me dig into this and see why there's so much more DNS activity than expected. It should be closer to 1440 DNS calls a day.

I'll see what I can find out! Thanks!!

**Comment by lux4rd0** [comment]
Hoping that there will be fewer DNS calls with my latest version. It's been rewritten from the ground up, and the requests for remote API calls are shared internally. I run several collectors for dozens of Tempest devices, so I'm unable to parse out specifics - but let me know if it's still an issue! Thanks!
