### ISSUE TITLE
InfluxDB 2.x Support

### ISSUE THREAD

**Issue by paulhugill** [lux4rd0/weatherflow-collector#11]
Do you have any plans for upgrading/supporting InfluxDB 2.x?

I think it is a pretty large amount of work, not least just adjusting all the queries on the dashboards!

You've put a lot of effort into this and it looks really great, so I'm trying to decide if I am best to use your AIO or spin up an InfluxDB 1.8 server just for the weatherflow data.
I think trying to build on what you have for 2.x by myself is likely a bit beyond me, but I could probably get somewhere based off of this inspiration.

Thanks
Paul

**Comment by lux4rd0** [comment]
@paulhugill 

Appreciate the message. I took a look at upgrading to InfluxDB 2.x and didn't find any particular usefulness to doing so. I'd have to start everything over for literally no immediate benefit that I can see. The dashboards would look the same, but I'd have to redo all queries and rebuild the collector. Indeed, when 1.8 is no longer supported with security patches or if other community members ask for it - I'll have another go at it... That and when Grafana builds a nicer UI for creating the Flux queries. :)

I'll add a to-do in my feature tracking in case I get inspired! :)

**Comment by paulhugill** [comment]
Sounds good, thanks for the reply.
I definitely thought it was going to be a lot of effort for very little (if any) benefit for you.
I'll have a think on whether I'll just spin up a separate 1.8 instance or spend the time to try and convert things myself.
If you end up looking at it, I'd be happy to help if I can.

**Comment by lux4rd0** [comment]
Working on InfluxDB v2 collector...

**Comment by disruptivepatternmaterial** [comment]
so I was doing some housekeeping and I noticed that :latest on the docker pulls a very old version; I tried to use the newer tag and it seems to use influx 2.0. I came here and saw this and it is still open.

But the readme doesnt reference influx 2.0.

Can you help me understand what that state is and all that jazz? Appreciated.

**Comment by lux4rd0** [comment]
The latest version finally releases! Whew! Who knew it would take 3-4 major rewrites as I was figuring out how to get better at writing Python. :) This version now supports InfluxDB V2, but it's drastically different under the covers than I had before. Probably could have updated the older version quite quickly and kept it the same. Sorry for the forever delay on that!!
