### ISSUE TITLE
Change Grafana Dashboards from Imperial to Metric

### ISSUE THREAD

**Issue by ruaan-deysel** [lux4rd0/weatherflow-collector#13]
Hello,

I noticed the dashboards all use imperial values. Fahrenheit, miles, etc. I tried changing from Fahrenheit to Celsius but looks like there's some math that needs to change for it to display it correctly in Celcius.

How difficult is it to change the reports to show metric values?

Cheers

**Comment by ojones117** [comment]
@ruaandeysel  - What was your fix? Did you manually edit the dashboards?

**Comment by ruaan-deysel** [comment]
@ojones117 I manually edited the dashboards and removed the math calculations. I also changed the measurement units from imperial to metric values. Took a bit of time to change but it’s working fine.

**Comment by MrColeyC** [comment]
@ruaandeysel do you have diffs?
