### ISSUE TITLE
Provisioning YAML for the ds and dashboard?

### ISSUE THREAD

**Issue by disruptivepatternmaterial** [lux4rd0/weatherflow-collector#14]
Any chance you have yamls for your dashboards and the correct datasource? Would make importing these and maintaining them super easy: we'd be able to drop these into the provisioning folder.

Thanks!!!!

**Comment by lux4rd0** [comment]
Each of the dashboards is now in the Grafana dashboards folder! I know this is super old, but they're all JSON and depend on everybody's particular data sources. I've now set up a variable for data sources, so it should be easy to enjoy them going forward. Thanks!
