### ISSUE TITLE
Issue with v3.5.3 arm docker images

### ISSUE THREAD

**Issue by ojones117** [lux4rd0/weatherflow-collector#19]
Running into an issue with v3.5.3 on a Raspberry Pi.

It looks like the new docker images are duplicated for arm and arm64 tags 
```

lux4rd0/weatherflow-collector   latest-arm     60183551f4db   36 hours ago    458MB
lux4rd0/weatherflow-collector   latest-arm64   60183551f4db   36 hours ago    458MB
```

After updating to the v3.5.3 release the following docker-compose.yml configuration isn't valid (which was previously OK)
    image: lux4rd0/weatherflow-collector:latest-arm

With the container starting with the following errors
```
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
standard_init_linux.go:228: exec user process caused: exec format error
```

```
CONTAINER ID   IMAGE                                      COMMAND                  CREATED         STATUS                  PORTS                                           NAMES
5e9eb66c4b93   lux4rd0/weatherflow-collector:latest-arm   "/usr/bin/dumb-init …"   4 seconds ago   Up Less than a second   0.0.0.0:50222->50222/udp, :::50222->50222/udp   weatherflow-collector

```

I also checked here - https://hub.docker.com/r/lux4rd0/weatherflow-collector/tags 

and the digest shows the same for both arm and arm64 images.

**Comment by lux4rd0** [comment]
@ojones117 - you're right!!! Will fix ASAP. Thanks for letting me know!!

**Comment by lux4rd0** [comment]
@ojones117 - I ran a build and pushed 3.5.2 and latest to docker. It ended up being a really old docker image running Debian Stretch, and I needed to find a way to switch everything to archive.debian.org to make it work. Please try it out when you get a moment.

I'll look to get a newer base image made since I'm relying on Grafana Promtail, and they haven't updated in quite some time...

**Comment by ojones117** [comment]
@lux4rd0 - Thanks for looking into this so quickly!

I pulled the latest-arm tag and am back up and running again.

And thanks as well for this fantastic project!
