### ISSUE TITLE
Errors in log file

### ISSUE THREAD

**Issue by vellanix** [lux4rd0/weatherflow-collector#20]
I'm using the collector in both REST and remote socket, and everything it's fine except a couple of error in the LOG file

remote-rest: Fri Jul 21 11:45:22 CEST 2023 - Tempest_cv precip_accum_local_yesterday_final is null
remote-rest: Fri Jul 21 11:45:22 CEST 2023 - Tempest_cv precip_minutes_local_yesterday_final is null
remote-rest: Fri Jul 21 11:45:22 CEST 2023 - Tempest_cv precip_analysis_type_yesterday is null
remote-socket: pulse_adj_ob_time is null
remote-socket: pulse_adj_ob_wind_avg is null
remote-socket: pulse_adj_ob_temp is null

The strange thing is that the DB seems to be correct.
Any Idea?
Thank you

**Comment by lux4rd0** [comment]
@vellanix, those three data elements seem to be undocumented by WeatherFlow, so I tossed them into a null value to not mess up the push to InfluxDB in case some systems use them. I'll keep an eye on it and see if I can find some details on it.
