### ISSUE TITLE
4.0 pushed to dockerhub?

### ISSUE THREAD

**Issue by krohrsb** [lux4rd0/weatherflow-collector#21]
This is more of a question. I don't see recent changes to this repo however I do see a new docker tag pushed to dockerhub.

https://hub.docker.com/layers/lux4rd0/weatherflow-collector/4.0.0/images/sha256-d5f2a1f22572438b063d3e97cec7dafee9c5c41e0011cab211f12fb85755dcac?context=explore

I'm curious if there is any background here.

Thanks!

**Comment by lux4rd0** [comment]
Hi @krohrsb - I updated the collector to use InfluxDB2 instead of 1.8. I'm testing it on a newer branch and having a few others try it—no other real updates. :) Look for a release coming next week, hopefully.

**Comment by krohrsb** [comment]
Fair enough. I use renovate locally in my homelab to issue pull requests for updated dependencies of various types which led me to the 4.0 tag and was curious since i couldn't find references to it. I'll await info in the near future. Thanks.

**Comment by krispayne** [comment]
@lux4rd0 any chance the 4.0.0-arm64 docker container could be published to test? I'm setting up for the first time but only use influxdb v2. Anxious to try and could provide some feedback if needed?
