### ISSUE TITLE
What if my hub is on a separate subnet?

### ISSUE THREAD

**Issue by perfectly-preserved-pie** [lux4rd0/weatherflow-collector#23]
Hi,

I'm not seeing an option that would tell weatherflow-collector to listen to a specific subnet using the local UDP option. For example, My Docker host is on 192.168.1.x, but my Weatherflow hub is on 192.168.4.x. I'm not understanding how to set it to so it'll listen to that subnet instead of the Docker host's. I have firewall rules correctly configured and can ping the hub from the Docker host.

**Comment by lux4rd0** [comment]
Hi @perfectly-preserved-pie  - currently, it's set to listen to 0.0.0.0 - which by default will listen to all network adapters that have access to all of your subnets. The hub is the one that sprays out - but perhaps it's only set to spray out to the local network. Subnets should be fine - unless they're actually segmented VLANs. My hub is on a different subnet, but my subnet mask is 255.255.192.0. I'll dig into this and see what I can find out.

**Comment by lux4rd0** [comment]
The new version of my collector allows you to change the host and port and lets you interact with other listeners simultaneously. Let me know if this helps out! Thanks!
